### ISSUE TITLE
[milestone] v1

### ISSUE THREAD

**Issue by jcbhmr** [jcbhmr/configure-executable-action#2]
related project to
https://github.com/jcbhmr/configure-bun-action
https://github.com/jcbhmr/configure-deno-action

- [ ] prepare a hello world example "hello-world-executable-action"
- [ ] make it work
- [ ] make it work with bash on linux & .bat on windows
- [ ] make it work with exe on windows & idk on linux/mac
- [ ] add note about bash to readme
- [ ] revamp readme to be more informative and friendly

**Comment by jcbhmr** [comment]
recently had the idea to do some segmentation between the preparation stage and the actual runtime stage while still treating the runtime stage as actual ts code and not just js assets.

on the below scale
```
raw assets | src subfolder | subproject | separate repo
                 ^^ this is a good spot for separation
```

anyways tree thing
```
readme
license
package.json
src/
  main.ts
  utils.ts
  runtime/
    main.ts
    pre.ts
    post.ts
    utils.ts
```

then use TWO vite builds to bundle the prep step src/main.ts and then second src/runtime/(main|pre|post).ts in addition.

just an idea tho might change it who knows
